name: Test CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Restore lerna
      uses: actions/cache@v3
      with:
        path: |
          - node_modules/
          - "**/node_modules/"
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    
    - run: npm config set '//npm-registry.deip.world/:_authToken' "${CASIMIR_NPM_TOKEN}"
    - run: npm i && npm run bootstrap:ci
      env:
        CASIMIR_NPM_TOKEN: ${{ secrets.CASIMIR_NPM_TOKEN }}
    - run: npm run test